#!/usr/bin/env bash

usage(){
echo
echo " _____                      _                  _ ";
echo "/  __ \                    | |                | |";
echo "| /  \/ _ __  _   _  _ __  | |_   ___    ___  | |";
echo "| |    | '__|| | | || '_ \ | __| / _ \  / _ \ | |";
echo "| \__/\| |   | |_| || |_) || |_ | (_) || (_) || |";
echo " \____/|_|    \__, || .__/  \__| \___/  \___/ |_|";
echo "               __/ || |                          ";
echo "              |___/ |_|                          ";
echo "                                                 ";
echo "Simple OpenSSL AES Enc/De/Crypt Tool"
echo -e "-----------------------------------------------"
echo "Encrypt a file/string with AES-128-CBC w/ Base64  "
echo -e "-----------------------------------------------"

echo "Usage: $0 <-e/--encrypt>|<-d/--decrypt> "
echo "        encrypt a file or string: $0 -e <string/file> <passphrase>"
echo "        decrypt a file pr string: $0 -d <string/file> <passphrase>"
}

enc(){
  case $1 in
  -h|--help) echo "Encrypt a file/string with AES-128-CBC w/ Base64 "
             echo "                   enc <string> <password>"
             echo "                   enc <file> <password>  "
  ;;

  *)
  test -f "$1" && is_File=true || is_File=false
  if $is_File; then
    cat "$1" | openssl enc -base64 -aes-128-cbc -a -salt -pass pass:"$2"
  else
    echo "$1" | openssl enc -base64 -aes-128-cbc -a -salt -pass pass:"$2"
  fi
  ;;
  esac
}


dec(){

  case $1 in
  -h|--help) echo  "Decrypt a file/string with AES-128-CBC w/ Base64 "
             echo   "                  dec <string> <password>"
             echo   "                  dec <file> <password>"

  ;;

  *)
  test -f "$1" && is_File=true || is_File=false
  if $is_File; then
    cat "$1" | openssl enc -d -base64 -aes-128-cbc -a -salt -pass pass:"$2"
  else
    echo "$1" | openssl enc -d -base64 -aes-128-cbc -a -salt -pass pass:"$2"
  fi
  ;;
  esac
}




case "$1" in
-e|--encrypt)
enc "$2" "$3"
;;
-d|--decrypt)
dec "$2" "$3"
;;
-h|--help)
usage
;;
*)
echo "Invalid option. Run $0 --help for usage"
;;
esac
